[package]
name = "elastic-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "*"
prost = "*"
prost-types = "*"
elasticsearch = "8.5.0-alpha.1"
serde_json = "*"
serde_yaml = "*"
chrono = "*"